export const portfolioData = [
  {
    "id": 1,
    "imageUrl": "content/img/portfolio/weather.svg",
    "altText": "Toronto weather json data api site",
    "title": "React.js Weather App",
    "name": "React.js Weather App",
    "description": "A personal project where I worked with openweather API, React.js, and Netlify to host a weather application.",
    "siteUrl": "https://openweather-react.netlify.com/",
    "siteAria": "View React.js Weather App portfolio website",
    "repoUrl": "https://github.com/andydurette/openweather-react",
    "repoAria": "View React.js Weather App portfolio repo",
  },
  {
    "id": 2,
    "imageUrl": "content/img/portfolio/fit.svg",
    "altText": "code quiz",
    "title": "code quiz",
    "name": "Fitness Tracker",
    "description": "Application built in my Georgia Tech Fullstack course, using a mongo database and node for crud operations.",
    "siteUrl": "https://workout-tracker206.herokuapp.com",
    "siteAria": "View code quiz website",
    "repoUrl": "https://github.com/steven-f206/Workout-Tracker",
    "repoAria": "View code quiz github repository",
  },
  {
    "id": 3,
    "imageUrl": "content/img/portfolio/team-profile.svg",
    "altText": "Team Profile App",
    "title": "Team Profile App",
    "name": "Team Profile App",
    "description": "Node CLI Application built in my Georgia Tech Fullstack course, app handles requests to build a team site.",
    "siteUrl": "",
    "siteAria": "View Team Profile App",
    "repoUrl": "https://github.com/steven-f206/Team-Profile-Generator",
    "repoAria": "View the Team Profile App repository",
  },
  {
    "id": 4,
    "imageUrl": "content/img/portfolio/employee-tracker.svg",
    "altText": "Employee tracker app",
    "title": "Employee tracker",
    "name": "Employee tracker",
    "description": "Node CLI Application built in my Georgia Tech Fullstack course, updates a mySQL database of employee info.",
    "siteUrl": "",
    "siteAria": "View Employee tracker app",
    "repoUrl": "https://github.com/steven-f206/Employee-Tracker",
    "repoAria": "View Employee tracker app",
  },
  {
    "id": 5,
    "imageUrl": "content/img/portfolio/pass-gen.svg",
    "altText": "Password Generator app",
    "title": "Password Generator app",
    "name": "Password Generator",
    "description": "Small Application where you can generate a password based off you own choice of requirements to be met.",
    "siteUrl": "https://steven-f206.github.io/Password-Generator/",
    "siteAria": "View password generator website",
    "repoUrl": "https://github.com/steven-f206/Password-Generator",
    "repoAria": "View password-generator github repository",
  },
  {
    "id": 6,
    "imageUrl": "content/img/portfolio/g-book.svg",
    "altText": "Google Books",
    "title": "Google Books",
    "name": "MERN Stack Google Books",
    "description": "Application built using the MERN Stack, created to add and remove google books api data from a database.",
    "siteUrl": "https://sf-react-google-books-app.herokuapp.com/",
    "siteAria": "MERN Stack Google Books website",
    "repoUrl": "https://github.com/steven-f206/Google-Books-Search",
    "repoAria": "MERN Stack Google Books repository",
  }
]




